sh tmp-time-test.sh 4 LOG - -
sh tmp-time-test.sh 4 TABLE SINGLE -
sh tmp-time-test.sh 4 TABLE SINGLE,SSE -
sh tmp-time-test.sh 4 TABLE DOUBLE -
sh tmp-time-test.sh 4 TABLE DOUBLE -
sh tmp-time-test.sh 4 TABLE QUAD -
sh tmp-time-test.sh 4 TABLE QUAD,LAZY -
sh tmp-time-test.sh 4 BYTWO_p - - 
sh tmp-time-test.sh 4 BYTWO_b - - 
sh tmp-time-test.sh 4 BYTWO_p SSE - 
sh tmp-time-test.sh 4 BYTWO_b SSE - 
